main.o: main.cpp
	g++ main.cpp -I/opt/homebrew/Cellar/sfml/2.5.1_1/include/ -L//opt/homebrew/Cellar/sfml/2.5.1_1/lib -lsfml-graphics -lsfml-window -lsfml-system
	./a.out

programout: main.o
	g++ main.o -o programout
	
	
